# Generated by Django 5.2.7 on 2025-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável para a empresa', max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('RM', 'Administrador RM'), ('COMPANY_ADMIN', 'Administrador da Empresa'), ('COMPANY_USER', 'Usuário da Empresa')], default='COMPANY_USER', max_length=20, verbose_name='Função'),
        ),
    ]
