# Generated by Django 5.2.7 on 2025-10-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_slug_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(help_text='URL amigável para a empresa', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
