# Generated by Django 5.2.7 on 2025-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_rm_superusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctomapfile',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Análise'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='analysis_results',
            field=models.JSONField(blank=True, default=dict, verbose_name='Resultados da Análise'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='coordinates_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Coordenadas'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='file_type',
            field=models.CharField(choices=[('kml', 'KML'), ('kmz', 'KMZ'), ('csv', 'CSV'), ('xls', 'XLS'), ('xlsx', 'XLSX')], default='csv', max_length=10, verbose_name='Tipo de Arquivo'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='issues_found',
            field=models.JSONField(blank=True, default=list, verbose_name='Problemas Encontrados'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status de Processamento'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo de Processamento (s)'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, verbose_name='Recomendações'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ctomapfile',
            name='viability_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score de Viabilidade'),
        ),
        migrations.AddIndex(
            model_name='ctomapfile',
            index=models.Index(fields=['company', 'processing_status'], name='core_ctomap_company_927d18_idx'),
        ),
        migrations.AddIndex(
            model_name='ctomapfile',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='core_ctomap_uploade_3170b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ctomapfile',
            index=models.Index(fields=['file_type', 'is_processed'], name='core_ctomap_file_ty_6136c2_idx'),
        ),
    ]
