# Generated by Django 5.2.7 on 2025-11-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_ticket_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_company_26eb8a_idx',
            old_name='core_ticket_company_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_created_c1f922_idx',
            old_name='core_ticket_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_assigne_833ed1_idx',
            old_name='core_ticket_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_ticket__cfa6c8_idx',
            old_name='core_ticket_number_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='core_ticket_ticket__fd8c72_idx',
            old_name='core_ticketm_ticket_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='core_ticket_sent_by_667a11_idx',
            old_name='core_ticketm_sent_by_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='core_ticket_read_fe7de9_idx',
            old_name='core_ticketm_read_idx',
        ),
    ]
