# Generated by Django 5.2.7 on 2025-11-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_ticket_company_idx_core_ticket_company_26eb8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Força a mudança de senha no primeiro acesso', verbose_name='Deve mudar senha'),
        ),
    ]
