# Generated by Django 4.2.25 on 2025-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(db_index=True, max_length=500, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('endereco_completo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache de Geocodificação',
                'verbose_name_plural': 'Cache de Geocodificações',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ViabilidadeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('resultado', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cache de Viabilidade',
                'verbose_name_plural': 'Cache de Viabilidades',
                'indexes': [models.Index(fields=['lat', 'lon'], name='ftth_viewer_lat_608d76_idx')],
                'unique_together': {('lat', 'lon')},
            },
        ),
        migrations.CreateModel(
            name='CTOFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('kml', 'KML'), ('kmz', 'KMZ'), ('csv', 'CSV'), ('xls', 'XLS'), ('xlsx', 'XLSX')], max_length=10)),
                ('caminho', models.FilePathField(max_length=1000)),
                ('total_pontos', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arquivo CTO',
                'verbose_name_plural': 'Arquivos CTO',
                'ordering': ['nome'],
                'unique_together': {('nome', 'tipo')},
            },
        ),
    ]
