# Generated by Django 5.2.7 on 2025-11-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_flask_integration_fields'),
        ('ftth_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='viabilidadecache',
            name='ftth_viewer_lat_608d76_idx',
        ),
        migrations.AlterUniqueTogether(
            name='viabilidadecache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='viabilidadecache',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viability_caches', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='viabilidadecache',
            unique_together={('lat', 'lon', 'company')},
        ),
        migrations.AddIndex(
            model_name='viabilidadecache',
            index=models.Index(fields=['lat', 'lon', 'company'], name='ftth_viewer_lat_e90c5a_idx'),
        ),
    ]
